# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0002_auto_20160706_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='designer',
            field=models.CharField(max_length=225, verbose_name=b'Mention any software you worked on(photoshop etc)'),
        ),
    ]
