# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0002_auto_20160709_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='warn_time',
            field=models.IntegerField(default=10),
        ),
    ]
