# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0002_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='short_name',
            field=models.CharField(default='Algorithm', max_length=100),
        ),
    ]
