# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0002_delete_pythonregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=5000),
        ),
    ]
