# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-29 13:54
from __future__ import unicode_literals

import Exam_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0003_algorithm_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='active',
            field=models.BooleanField(default=False, validators=[Exam_portal.models.algorithm_validator]),
        ),
    ]
