# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0003_test_warn_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
