# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0005_auto_20160710_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='warn_time',
            field=models.IntegerField(default=1),
        ),
    ]
