# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0007_examstarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField()),
            ],
        ),
    ]
