# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0009_auto_20160721_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='choice',
            field=models.CharField(max_length=2000),
        ),
    ]
