# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0010_auto_20160722_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
