# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-24 18:06
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0012_auto_20160724_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
