# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0014_auto_20160725_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='refresh_flag',
            field=models.IntegerField(default=0),
        ),
    ]
