# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0016_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 4, 6, 9, 36, 515651)),
        ),
    ]
