# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0017_student_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 22, 13, 38, 59, 594532)),
        ),
    ]
