# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0018_auto_20160922_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 22, 13, 40, 19, 557385)),
        ),
    ]
