# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_portal', '0019_auto_20160922_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
